### ISSUE TITLE
HD4000 backlight too dark 10.11

### ISSUE THREAD

**Issue by DiggerFraggot** [RehabMan/OS-X-Intel-Backlight#1]
In console i see that PNLF patch was not found but it is in DSDT. So the display stays at 30% brightness.

**Comment by RehabMan** [comment]
Use the forums to debug your configuration mistake.  This site is only for bug reports.

**Comment by DiggerFraggot** [comment]
It is a bug because in 10.10 it works without any problem

**Comment by RehabMan** [comment]
10.10 is completely different than 10.11.  You should use the forums.
