### ISSUE TITLE
Please ignore

### ISSUE THREAD

**Issue by RaeesBhatti** [RehabMan/OS-X-Intel-Backlight#2]
Nothing... :D

**Comment by RehabMan** [comment]
It works.

But your laptop has a guide: 

http://www.tonymacx86.com/el-capitan-laptop-guides/189416-guide-hp-probook-elitebook-zbook-using-clover-uefi-hotpatch-10-11-a.html

**Comment by raeesiqbal** [comment]
Thank you!! But there is no `.aml` for HP Probook 440 G3, which one do you suggest I should use.

**Comment by RehabMan** [comment]
The AMLs you need are created when you run ‘make’.

If you need clarification, reply in the guide thread.
