### ISSUE TITLE
Flickering/Blinking screen elements

### ISSUE THREAD

**Issue by johannes87** [RehabMan/OS-X-Intel-Backlight#3]
There seems to be a problem with flickering on certain panels in OS X. The flickering doesn't happen on Linux, so it's not a hardware problem.

These threads mention them: 

http://www.insanelymac.com/forum/topic/312019-display-flickeringblinking-looks-like-a-low-refresh-rate-thinkpad-x220/
http://www.tonymacx86.com/threads/blinking-screen-elements-low-refresh-rate.153478/
http://www.tonymacx86.com/threads/lenovo-x220-refresh-rate.189611/

Could this be related to this kext? From the looks, I would guess it could be an issue with the backlight. (just a guess, of course)

**Comment by RehabMan** [comment]
Not related to IntelBacklight.kext.  It has something to do with OS X compatibility with certain displays.  My ProBooks have the problem, but not my u430.  I don't remember it on my Haswell HP Envy either.

It is probably EDID related or just something in the way OS  X implements dithering.

At any rate, you will see it even if you implement backlight with AppleBacklight.kext (requires patches).

**Comment by johannes87** [comment]
In what way does OS X use dithering? I.e., where in the "output pipeline" is dithering used, and what is its use?

**Comment by RehabMan** [comment]
No idea.
