### ISSUE TITLE
download Link is a dead link

### ISSUE THREAD

**Issue by 0xMH** [RehabMan/OS-X-Intel-Backlight#5]
https://bitbucket.org/RehabMan/os-x-intel-backlight/downloads

**Comment by RehabMan** [comment]
It is a silly change made by bitbucket/atlassian

Add slash:
https://bitbucket.org/RehabMan/os-x-intel-backlight/downloads/

**Comment by RehabMan** [comment]
I have reported the issue to bitbucket via a support ticket.

**Comment by RehabMan** [comment]
fixed the link in the README, even though word from bitbucket is they will fix in about a week.
