### ISSUE TITLE
Add new light levels but not work 

### ISSUE THREAD

**Issue by link-duan** [RehabMan/OS-X-Intel-Backlight#6]
My screen is too light for me at night.
I want to set the min light level lower. So I add a new line to "BacklightLevels".
This is what I changed:

 Device (PNLF)
            {
                Name (_ADR, Zero)
                Name (_HID, EisaId ("APP0002"))
                Name (_CID, "backlight")
                Name (_UID, 10)
                Name (_STA, 0x0B)
                Method (RMCF)
                {
                    Return(Package()
                    {
                        "PWMMax", 0,
                        "BacklightMin", 10,
                        "BacklightMax", 0xad9,
                        "BacklightLevelsScale", 0xad9,
                        "BacklightLevels", Package()
                        {
                            Package(){},
                            0,
                            10, 11, 13, 16, // line added
                            18, 19, 21, 24, // line added
                            35, 39, 44, 50,
                            58, 67, 77, 88,
                            101, 115, 130, 147,
                            165, 184, 204, 226,
                            249, 273, 299, 326,
                            354, 383, 414, 446,
                            479, 514, 549, 587,
                            625, 665, 706, 748,
                            791, 836, 882, 930,
                            978, 1028, 1079, 1132,
                            1186, 1241, 1297, 1355,
                            1414, 1474, 1535, 1598,
                            1662, 1728, 1794, 1862,
                            1931, 2002, 2074, 2147,
                            2221, 2296, 2373, 2452,
                            2531, 2612, 2694, 0xad9,
                        },
                    })
                }
            }

**Comment by RehabMan** [comment]
It is wrong.
You must provide exactly the same number of backlight levels as originally present.
(65 levels including the 0/black level)
